name: CI/CD — Hotfix → STG

on:
  push:
    branches:
      - hotfix/**
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: stg
      webapp-name: stg-demo-helloworld-api
      azure-client-id: 3d291ad9-9d36-4f52-be2c-6b385a085ffb
      build-label: ${{ needs.build.outputs.build-label }}
