name: CI/CD — Main → PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
      webapp-name: prod-ue2-api-fc-base-app
      azure-client-id: '' # TODO: prod App Registration client ID
      build-label: ${{ needs.build.outputs.build-label }}
